import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import { Computer } from '../types/index'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [computers, setComputers] = useState<Array<Computer>>([]);
  const [load, setLoad] = useState(true);
  useEffect(() => {
    let mounted = true;
    console.log('useEffect');
    if (mounted) {
      fetch('http://192.168.13.5:3000/getComputers')
        .then(response => {
          response.json()
            .then(data => {
              setComputers(data)
              setLoad(false);
            });
        })
    }
    return () => { mounted = false }
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {load ? '' :
          computers.map(c => (
            <Card key={c.Ip} computer={c}></Card>
          ))
        }
      </main>
    </div>
  )
}

export default Home
